// GENERATED by tools/pixelart/import_assets.py from the portrait sheets; do not edit by hand.
package com.example.blacksmithproject.ui

import com.example.blacksmithproject.R

/** Drawable and content box per appearance key (the key is the asset ID a hero stores, never an index). */
internal object PortraitArt {
    /** The one switch for the second face set: it joins the lookup only after it has been verified on a device. */
    const val SECOND_SET_ENABLED = false

    /** [resName] is the drawable's resource name; the box (left, top, right, bottom; right and bottom exclusive) holds the pixels that are not empty. */
    class Entry(val drawable: Int, val resName: String, val left: Int, val top: Int, val right: Int, val bottom: Int)

    /** The 25 busts of concept sheet 3: transparent cut-outs, five per class. */
    val base: Map<String, Entry> = mapOf(
        "portrait_guardian_0" to Entry(R.drawable.portrait_guardian_0, "portrait_guardian_0", 1, 1, 63, 60),
        "portrait_guardian_1" to Entry(R.drawable.portrait_guardian_1, "portrait_guardian_1", 1, 1, 63, 62),
        "portrait_guardian_2" to Entry(R.drawable.portrait_guardian_2, "portrait_guardian_2", 2, 1, 63, 59),
        "portrait_guardian_3" to Entry(R.drawable.portrait_guardian_3, "portrait_guardian_3", 1, 1, 63, 54),
        "portrait_guardian_4" to Entry(R.drawable.portrait_guardian_4, "portrait_guardian_4", 1, 1, 62, 63),
        "portrait_ranger_0" to Entry(R.drawable.portrait_ranger_0, "portrait_ranger_0", 1, 1, 63, 54),
        "portrait_ranger_1" to Entry(R.drawable.portrait_ranger_1, "portrait_ranger_1", 1, 1, 63, 59),
        "portrait_ranger_2" to Entry(R.drawable.portrait_ranger_2, "portrait_ranger_2", 1, 1, 63, 58),
        "portrait_ranger_3" to Entry(R.drawable.portrait_ranger_3, "portrait_ranger_3", 1, 1, 63, 56),
        "portrait_ranger_4" to Entry(R.drawable.portrait_ranger_4, "portrait_ranger_4", 1, 1, 63, 57),
        "portrait_duelist_0" to Entry(R.drawable.portrait_duelist_0, "portrait_duelist_0", 1, 1, 63, 54),
        "portrait_duelist_1" to Entry(R.drawable.portrait_duelist_1, "portrait_duelist_1", 1, 1, 63, 57),
        "portrait_duelist_2" to Entry(R.drawable.portrait_duelist_2, "portrait_duelist_2", 1, 1, 63, 54),
        "portrait_duelist_3" to Entry(R.drawable.portrait_duelist_3, "portrait_duelist_3", 1, 1, 63, 53),
        "portrait_duelist_4" to Entry(R.drawable.portrait_duelist_4, "portrait_duelist_4", 1, 1, 63, 57),
        "portrait_battlemage_0" to Entry(R.drawable.portrait_battlemage_0, "portrait_battlemage_0", 1, 1, 63, 58),
        "portrait_battlemage_1" to Entry(R.drawable.portrait_battlemage_1, "portrait_battlemage_1", 1, 1, 63, 58),
        "portrait_battlemage_2" to Entry(R.drawable.portrait_battlemage_2, "portrait_battlemage_2", 1, 1, 63, 58),
        "portrait_battlemage_3" to Entry(R.drawable.portrait_battlemage_3, "portrait_battlemage_3", 1, 1, 63, 57),
        "portrait_battlemage_4" to Entry(R.drawable.portrait_battlemage_4, "portrait_battlemage_4", 1, 1, 63, 61),
        "portrait_warden_0" to Entry(R.drawable.portrait_warden_0, "portrait_warden_0", 1, 1, 63, 60),
        "portrait_warden_1" to Entry(R.drawable.portrait_warden_1, "portrait_warden_1", 1, 1, 63, 58),
        "portrait_warden_2" to Entry(R.drawable.portrait_warden_2, "portrait_warden_2", 1, 1, 63, 59),
        "portrait_warden_3" to Entry(R.drawable.portrait_warden_3, "portrait_warden_3", 1, 1, 63, 62),
        "portrait_warden_4" to Entry(R.drawable.portrait_warden_4, "portrait_warden_4", 1, 1, 63, 60),
    )

    /** Candidate second set as opaque 64 px tiles with their painted background. */
    val secondSet: Map<String, Entry> = mapOf(
        "portrait_v2_guardian_1" to Entry(R.drawable.portrait_v2_guardian_1, "portrait_v2_guardian_1", 0, 0, 64, 64),
        "portrait_v2_guardian_2" to Entry(R.drawable.portrait_v2_guardian_2, "portrait_v2_guardian_2", 0, 0, 64, 64),
        "portrait_v2_guardian_3" to Entry(R.drawable.portrait_v2_guardian_3, "portrait_v2_guardian_3", 0, 0, 64, 64),
        "portrait_v2_guardian_4" to Entry(R.drawable.portrait_v2_guardian_4, "portrait_v2_guardian_4", 0, 0, 64, 64),
        "portrait_v2_guardian_5" to Entry(R.drawable.portrait_v2_guardian_5, "portrait_v2_guardian_5", 0, 0, 64, 64),
        "portrait_v2_ranger_1" to Entry(R.drawable.portrait_v2_ranger_1, "portrait_v2_ranger_1", 0, 0, 64, 64),
        "portrait_v2_ranger_2" to Entry(R.drawable.portrait_v2_ranger_2, "portrait_v2_ranger_2", 0, 0, 64, 64),
        "portrait_v2_ranger_3" to Entry(R.drawable.portrait_v2_ranger_3, "portrait_v2_ranger_3", 0, 0, 64, 64),
        "portrait_v2_ranger_4" to Entry(R.drawable.portrait_v2_ranger_4, "portrait_v2_ranger_4", 0, 0, 64, 64),
        "portrait_v2_ranger_5" to Entry(R.drawable.portrait_v2_ranger_5, "portrait_v2_ranger_5", 0, 0, 64, 64),
        "portrait_v2_duelist_1" to Entry(R.drawable.portrait_v2_duelist_1, "portrait_v2_duelist_1", 0, 0, 64, 64),
        "portrait_v2_duelist_2" to Entry(R.drawable.portrait_v2_duelist_2, "portrait_v2_duelist_2", 0, 0, 64, 64),
        "portrait_v2_duelist_3" to Entry(R.drawable.portrait_v2_duelist_3, "portrait_v2_duelist_3", 0, 0, 64, 64),
        "portrait_v2_duelist_4" to Entry(R.drawable.portrait_v2_duelist_4, "portrait_v2_duelist_4", 0, 0, 64, 64),
        "portrait_v2_duelist_5" to Entry(R.drawable.portrait_v2_duelist_5, "portrait_v2_duelist_5", 0, 0, 64, 64),
        "portrait_v2_battlemage_1" to Entry(R.drawable.portrait_v2_battlemage_1, "portrait_v2_battlemage_1", 0, 0, 64, 64),
        "portrait_v2_battlemage_2" to Entry(R.drawable.portrait_v2_battlemage_2, "portrait_v2_battlemage_2", 0, 0, 64, 64),
        "portrait_v2_battlemage_3" to Entry(R.drawable.portrait_v2_battlemage_3, "portrait_v2_battlemage_3", 0, 0, 64, 64),
        "portrait_v2_battlemage_4" to Entry(R.drawable.portrait_v2_battlemage_4, "portrait_v2_battlemage_4", 0, 0, 64, 64),
        "portrait_v2_battlemage_5" to Entry(R.drawable.portrait_v2_battlemage_5, "portrait_v2_battlemage_5", 0, 0, 64, 64),
        "portrait_v2_warden_1" to Entry(R.drawable.portrait_v2_warden_1, "portrait_v2_warden_1", 0, 0, 64, 64),
        "portrait_v2_warden_2" to Entry(R.drawable.portrait_v2_warden_2, "portrait_v2_warden_2", 0, 0, 64, 64),
        "portrait_v2_warden_3" to Entry(R.drawable.portrait_v2_warden_3, "portrait_v2_warden_3", 0, 0, 64, 64),
        "portrait_v2_warden_4" to Entry(R.drawable.portrait_v2_warden_4, "portrait_v2_warden_4", 0, 0, 64, 64),
        "portrait_v2_warden_5" to Entry(R.drawable.portrait_v2_warden_5, "portrait_v2_warden_5", 0, 0, 64, 64),
    )

    /** The same keys as keyed cut-outs: only the tiles that passed the importer's checks and the review. */
    val secondSetCutouts: Map<String, Entry> = mapOf(
    )

    fun find(key: String, secondSet: Boolean = SECOND_SET_ENABLED): Entry? = base[key] ?: if (secondSet) this.secondSet[key] else null

    operator fun get(key: String): Entry? = find(key)
}
