// GENERATED by tools/pixelart/import_assets.py from the weapon master sheet; do not edit by hand.
package com.example.blacksmithproject.ui

import com.example.blacksmithproject.R

/** Drawable per weapon family, element row (base = no augment) and visual level 1..LEVELS. */
internal object WeaponArt {
    const val LEVELS = 8
    private val rows = listOf("base", "fire", "frost", "storm", "grave", "verdant", "sun")
    private val table: Map<String, Array<IntArray>> = mapOf(
        "sword" to arrayOf(
            intArrayOf(R.drawable.weapon_sword_base_1, R.drawable.weapon_sword_base_2, R.drawable.weapon_sword_base_3, R.drawable.weapon_sword_base_4, R.drawable.weapon_sword_base_5, R.drawable.weapon_sword_base_6, R.drawable.weapon_sword_base_7, R.drawable.weapon_sword_base_8),
            intArrayOf(R.drawable.weapon_sword_fire_1, R.drawable.weapon_sword_fire_2, R.drawable.weapon_sword_fire_3, R.drawable.weapon_sword_fire_4, R.drawable.weapon_sword_fire_5, R.drawable.weapon_sword_fire_6, R.drawable.weapon_sword_fire_7, R.drawable.weapon_sword_fire_8),
            intArrayOf(R.drawable.weapon_sword_frost_1, R.drawable.weapon_sword_frost_2, R.drawable.weapon_sword_frost_3, R.drawable.weapon_sword_frost_4, R.drawable.weapon_sword_frost_5, R.drawable.weapon_sword_frost_6, R.drawable.weapon_sword_frost_7, R.drawable.weapon_sword_frost_8),
            intArrayOf(R.drawable.weapon_sword_storm_1, R.drawable.weapon_sword_storm_2, R.drawable.weapon_sword_storm_3, R.drawable.weapon_sword_storm_4, R.drawable.weapon_sword_storm_5, R.drawable.weapon_sword_storm_6, R.drawable.weapon_sword_storm_7, R.drawable.weapon_sword_storm_8),
            intArrayOf(R.drawable.weapon_sword_grave_1, R.drawable.weapon_sword_grave_2, R.drawable.weapon_sword_grave_3, R.drawable.weapon_sword_grave_4, R.drawable.weapon_sword_grave_5, R.drawable.weapon_sword_grave_6, R.drawable.weapon_sword_grave_7, R.drawable.weapon_sword_grave_8),
            intArrayOf(R.drawable.weapon_sword_verdant_1, R.drawable.weapon_sword_verdant_2, R.drawable.weapon_sword_verdant_3, R.drawable.weapon_sword_verdant_4, R.drawable.weapon_sword_verdant_5, R.drawable.weapon_sword_verdant_6, R.drawable.weapon_sword_verdant_7, R.drawable.weapon_sword_verdant_8),
            intArrayOf(R.drawable.weapon_sword_sun_1, R.drawable.weapon_sword_sun_2, R.drawable.weapon_sword_sun_3, R.drawable.weapon_sword_sun_4, R.drawable.weapon_sword_sun_5, R.drawable.weapon_sword_sun_6, R.drawable.weapon_sword_sun_7, R.drawable.weapon_sword_sun_8),
        ),
        "axe" to arrayOf(
            intArrayOf(R.drawable.weapon_axe_base_1, R.drawable.weapon_axe_base_2, R.drawable.weapon_axe_base_3, R.drawable.weapon_axe_base_4, R.drawable.weapon_axe_base_5, R.drawable.weapon_axe_base_6, R.drawable.weapon_axe_base_7, R.drawable.weapon_axe_base_8),
            intArrayOf(R.drawable.weapon_axe_fire_1, R.drawable.weapon_axe_fire_2, R.drawable.weapon_axe_fire_3, R.drawable.weapon_axe_fire_4, R.drawable.weapon_axe_fire_5, R.drawable.weapon_axe_fire_6, R.drawable.weapon_axe_fire_7, R.drawable.weapon_axe_fire_8),
            intArrayOf(R.drawable.weapon_axe_frost_1, R.drawable.weapon_axe_frost_2, R.drawable.weapon_axe_frost_3, R.drawable.weapon_axe_frost_4, R.drawable.weapon_axe_frost_5, R.drawable.weapon_axe_frost_6, R.drawable.weapon_axe_frost_7, R.drawable.weapon_axe_frost_8),
            intArrayOf(R.drawable.weapon_axe_storm_1, R.drawable.weapon_axe_storm_2, R.drawable.weapon_axe_storm_3, R.drawable.weapon_axe_storm_4, R.drawable.weapon_axe_storm_5, R.drawable.weapon_axe_storm_6, R.drawable.weapon_axe_storm_7, R.drawable.weapon_axe_storm_8),
            intArrayOf(R.drawable.weapon_axe_grave_1, R.drawable.weapon_axe_grave_2, R.drawable.weapon_axe_grave_3, R.drawable.weapon_axe_grave_4, R.drawable.weapon_axe_grave_5, R.drawable.weapon_axe_grave_6, R.drawable.weapon_axe_grave_7, R.drawable.weapon_axe_grave_8),
            intArrayOf(R.drawable.weapon_axe_verdant_1, R.drawable.weapon_axe_verdant_2, R.drawable.weapon_axe_verdant_3, R.drawable.weapon_axe_verdant_4, R.drawable.weapon_axe_verdant_5, R.drawable.weapon_axe_verdant_6, R.drawable.weapon_axe_verdant_7, R.drawable.weapon_axe_verdant_8),
            intArrayOf(R.drawable.weapon_axe_sun_1, R.drawable.weapon_axe_sun_2, R.drawable.weapon_axe_sun_3, R.drawable.weapon_axe_sun_4, R.drawable.weapon_axe_sun_5, R.drawable.weapon_axe_sun_6, R.drawable.weapon_axe_sun_7, R.drawable.weapon_axe_sun_8),
        ),
        "spear" to arrayOf(
            intArrayOf(R.drawable.weapon_spear_base_1, R.drawable.weapon_spear_base_2, R.drawable.weapon_spear_base_3, R.drawable.weapon_spear_base_4, R.drawable.weapon_spear_base_5, R.drawable.weapon_spear_base_6, R.drawable.weapon_spear_base_7, R.drawable.weapon_spear_base_8),
            intArrayOf(R.drawable.weapon_spear_fire_1, R.drawable.weapon_spear_fire_2, R.drawable.weapon_spear_fire_3, R.drawable.weapon_spear_fire_4, R.drawable.weapon_spear_fire_5, R.drawable.weapon_spear_fire_6, R.drawable.weapon_spear_fire_7, R.drawable.weapon_spear_fire_8),
            intArrayOf(R.drawable.weapon_spear_frost_1, R.drawable.weapon_spear_frost_2, R.drawable.weapon_spear_frost_3, R.drawable.weapon_spear_frost_4, R.drawable.weapon_spear_frost_5, R.drawable.weapon_spear_frost_6, R.drawable.weapon_spear_frost_7, R.drawable.weapon_spear_frost_8),
            intArrayOf(R.drawable.weapon_spear_storm_1, R.drawable.weapon_spear_storm_2, R.drawable.weapon_spear_storm_3, R.drawable.weapon_spear_storm_4, R.drawable.weapon_spear_storm_5, R.drawable.weapon_spear_storm_6, R.drawable.weapon_spear_storm_7, R.drawable.weapon_spear_storm_8),
            intArrayOf(R.drawable.weapon_spear_grave_1, R.drawable.weapon_spear_grave_2, R.drawable.weapon_spear_grave_3, R.drawable.weapon_spear_grave_4, R.drawable.weapon_spear_grave_5, R.drawable.weapon_spear_grave_6, R.drawable.weapon_spear_grave_7, R.drawable.weapon_spear_grave_8),
            intArrayOf(R.drawable.weapon_spear_verdant_1, R.drawable.weapon_spear_verdant_2, R.drawable.weapon_spear_verdant_3, R.drawable.weapon_spear_verdant_4, R.drawable.weapon_spear_verdant_5, R.drawable.weapon_spear_verdant_6, R.drawable.weapon_spear_verdant_7, R.drawable.weapon_spear_verdant_8),
            intArrayOf(R.drawable.weapon_spear_sun_1, R.drawable.weapon_spear_sun_2, R.drawable.weapon_spear_sun_3, R.drawable.weapon_spear_sun_4, R.drawable.weapon_spear_sun_5, R.drawable.weapon_spear_sun_6, R.drawable.weapon_spear_sun_7, R.drawable.weapon_spear_sun_8),
        ),
        "bow" to arrayOf(
            intArrayOf(R.drawable.weapon_bow_base_1, R.drawable.weapon_bow_base_2, R.drawable.weapon_bow_base_3, R.drawable.weapon_bow_base_4, R.drawable.weapon_bow_base_5, R.drawable.weapon_bow_base_6, R.drawable.weapon_bow_base_7, R.drawable.weapon_bow_base_8),
            intArrayOf(R.drawable.weapon_bow_fire_1, R.drawable.weapon_bow_fire_2, R.drawable.weapon_bow_fire_3, R.drawable.weapon_bow_fire_4, R.drawable.weapon_bow_fire_5, R.drawable.weapon_bow_fire_6, R.drawable.weapon_bow_fire_7, R.drawable.weapon_bow_fire_8),
            intArrayOf(R.drawable.weapon_bow_frost_1, R.drawable.weapon_bow_frost_2, R.drawable.weapon_bow_frost_3, R.drawable.weapon_bow_frost_4, R.drawable.weapon_bow_frost_5, R.drawable.weapon_bow_frost_6, R.drawable.weapon_bow_frost_7, R.drawable.weapon_bow_frost_8),
            intArrayOf(R.drawable.weapon_bow_storm_1, R.drawable.weapon_bow_storm_2, R.drawable.weapon_bow_storm_3, R.drawable.weapon_bow_storm_4, R.drawable.weapon_bow_storm_5, R.drawable.weapon_bow_storm_6, R.drawable.weapon_bow_storm_7, R.drawable.weapon_bow_storm_8),
            intArrayOf(R.drawable.weapon_bow_grave_1, R.drawable.weapon_bow_grave_2, R.drawable.weapon_bow_grave_3, R.drawable.weapon_bow_grave_4, R.drawable.weapon_bow_grave_5, R.drawable.weapon_bow_grave_6, R.drawable.weapon_bow_grave_7, R.drawable.weapon_bow_grave_8),
            intArrayOf(R.drawable.weapon_bow_verdant_1, R.drawable.weapon_bow_verdant_2, R.drawable.weapon_bow_verdant_3, R.drawable.weapon_bow_verdant_4, R.drawable.weapon_bow_verdant_5, R.drawable.weapon_bow_verdant_6, R.drawable.weapon_bow_verdant_7, R.drawable.weapon_bow_verdant_8),
            intArrayOf(R.drawable.weapon_bow_sun_1, R.drawable.weapon_bow_sun_2, R.drawable.weapon_bow_sun_3, R.drawable.weapon_bow_sun_4, R.drawable.weapon_bow_sun_5, R.drawable.weapon_bow_sun_6, R.drawable.weapon_bow_sun_7, R.drawable.weapon_bow_sun_8),
        ),
        "dagger" to arrayOf(
            intArrayOf(R.drawable.weapon_dagger_base_1, R.drawable.weapon_dagger_base_2, R.drawable.weapon_dagger_base_3, R.drawable.weapon_dagger_base_4, R.drawable.weapon_dagger_base_5, R.drawable.weapon_dagger_base_6, R.drawable.weapon_dagger_base_7, R.drawable.weapon_dagger_base_8),
            intArrayOf(R.drawable.weapon_dagger_fire_1, R.drawable.weapon_dagger_fire_2, R.drawable.weapon_dagger_fire_3, R.drawable.weapon_dagger_fire_4, R.drawable.weapon_dagger_fire_5, R.drawable.weapon_dagger_fire_6, R.drawable.weapon_dagger_fire_7, R.drawable.weapon_dagger_fire_8),
            intArrayOf(R.drawable.weapon_dagger_frost_1, R.drawable.weapon_dagger_frost_2, R.drawable.weapon_dagger_frost_3, R.drawable.weapon_dagger_frost_4, R.drawable.weapon_dagger_frost_5, R.drawable.weapon_dagger_frost_6, R.drawable.weapon_dagger_frost_7, R.drawable.weapon_dagger_frost_8),
            intArrayOf(R.drawable.weapon_dagger_storm_1, R.drawable.weapon_dagger_storm_2, R.drawable.weapon_dagger_storm_3, R.drawable.weapon_dagger_storm_4, R.drawable.weapon_dagger_storm_5, R.drawable.weapon_dagger_storm_6, R.drawable.weapon_dagger_storm_7, R.drawable.weapon_dagger_storm_8),
            intArrayOf(R.drawable.weapon_dagger_grave_1, R.drawable.weapon_dagger_grave_2, R.drawable.weapon_dagger_grave_3, R.drawable.weapon_dagger_grave_4, R.drawable.weapon_dagger_grave_5, R.drawable.weapon_dagger_grave_6, R.drawable.weapon_dagger_grave_7, R.drawable.weapon_dagger_grave_8),
            intArrayOf(R.drawable.weapon_dagger_verdant_1, R.drawable.weapon_dagger_verdant_2, R.drawable.weapon_dagger_verdant_3, R.drawable.weapon_dagger_verdant_4, R.drawable.weapon_dagger_verdant_5, R.drawable.weapon_dagger_verdant_6, R.drawable.weapon_dagger_verdant_7, R.drawable.weapon_dagger_verdant_8),
            intArrayOf(R.drawable.weapon_dagger_sun_1, R.drawable.weapon_dagger_sun_2, R.drawable.weapon_dagger_sun_3, R.drawable.weapon_dagger_sun_4, R.drawable.weapon_dagger_sun_5, R.drawable.weapon_dagger_sun_6, R.drawable.weapon_dagger_sun_7, R.drawable.weapon_dagger_sun_8),
        ),
        "staff" to arrayOf(
            intArrayOf(R.drawable.weapon_staff_base_1, R.drawable.weapon_staff_base_2, R.drawable.weapon_staff_base_3, R.drawable.weapon_staff_base_4, R.drawable.weapon_staff_base_5, R.drawable.weapon_staff_base_6, R.drawable.weapon_staff_base_7, R.drawable.weapon_staff_base_8),
            intArrayOf(R.drawable.weapon_staff_fire_1, R.drawable.weapon_staff_fire_2, R.drawable.weapon_staff_fire_3, R.drawable.weapon_staff_fire_4, R.drawable.weapon_staff_fire_5, R.drawable.weapon_staff_fire_6, R.drawable.weapon_staff_fire_7, R.drawable.weapon_staff_fire_8),
            intArrayOf(R.drawable.weapon_staff_frost_1, R.drawable.weapon_staff_frost_2, R.drawable.weapon_staff_frost_3, R.drawable.weapon_staff_frost_4, R.drawable.weapon_staff_frost_5, R.drawable.weapon_staff_frost_6, R.drawable.weapon_staff_frost_7, R.drawable.weapon_staff_frost_8),
            intArrayOf(R.drawable.weapon_staff_storm_1, R.drawable.weapon_staff_storm_2, R.drawable.weapon_staff_storm_3, R.drawable.weapon_staff_storm_4, R.drawable.weapon_staff_storm_5, R.drawable.weapon_staff_storm_6, R.drawable.weapon_staff_storm_7, R.drawable.weapon_staff_storm_8),
            intArrayOf(R.drawable.weapon_staff_grave_1, R.drawable.weapon_staff_grave_2, R.drawable.weapon_staff_grave_3, R.drawable.weapon_staff_grave_4, R.drawable.weapon_staff_grave_5, R.drawable.weapon_staff_grave_6, R.drawable.weapon_staff_grave_7, R.drawable.weapon_staff_grave_8),
            intArrayOf(R.drawable.weapon_staff_verdant_1, R.drawable.weapon_staff_verdant_2, R.drawable.weapon_staff_verdant_3, R.drawable.weapon_staff_verdant_4, R.drawable.weapon_staff_verdant_5, R.drawable.weapon_staff_verdant_6, R.drawable.weapon_staff_verdant_7, R.drawable.weapon_staff_verdant_8),
            intArrayOf(R.drawable.weapon_staff_sun_1, R.drawable.weapon_staff_sun_2, R.drawable.weapon_staff_sun_3, R.drawable.weapon_staff_sun_4, R.drawable.weapon_staff_sun_5, R.drawable.weapon_staff_sun_6, R.drawable.weapon_staff_sun_7, R.drawable.weapon_staff_sun_8),
        ),
    )

    fun sprite(family: String, row: String, level: Int): Int? =
        table[family]?.get(rows.indexOf(row).coerceAtLeast(0))?.get((level - 1).coerceIn(0, LEVELS - 1))
}
